site_name: Fincepta CashFlow Intelligence API
theme:
  name: material
  logo: images/logo.png
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: fincepta-dark
      toggle:
        icon: material/brightness-7
        name: Light Mode
    # Palette toggle for dark mode
    - scheme: fincepta-light
      toggle:
        icon: material/brightness-4
        name: Dark Mode
  font:
    code: Attentica 4F
  features:
  - search
  - navigation.tracking
  - navigation.indexes
  - navigation.prune
extra_css:
  - stylesheets/extra.css
  
nav:
  - Overview: index.md
  - Enrich:
    - Enrich Report: enrich_report.md
    - Enrich Transaction: enrich_transactions.md
    - Feedback: feedback.md
  - Features: features.md
  - Score: 
    - Overview: score.md
    - Scores:
      - Cash Advance: models/cashadv.md
      - NSF Score: models/nsfscore.md
  - Combinations: combinations.md
  - Integrations: integrations.md
