site_name: Fincepta CashFlow UW API Doc
theme:
  name: material
  features:
  - search
  - navigation.tracking
  - navigation.indexes
  - navigation.prune
  
nav:
  - Overview: index.md
  - Enrich: enrich.md
  - Features: features.md
  - Score: 
    - Overview: score.md
    - Models:
      - Cash Advance: models/cashadv.md
      - NSF Score: models/nsfscore.md
  - Combinations: combinations.md
